### ISSUE TITLE
File Structure

### ISSUE THREAD

**Issue by DaveSalterM** [brad-wall01/Brews-Grooves#2]
Create basic file structure for project

- [x] index.html
- [x] defaultResults.html
- [x] musicMain.html
- [x] beerMain.html
- [x] mapResults.html

- [x] style.css

- [x] splash.js
- [x] defaultResults.js
- [x] musicMain.js
- [x] beerMain.js
- [x] mapResults.js

**Comment by brad-wall01** [comment]
added file structures and also created folders to include and organize the files
